config/routes.rb
# -*- coding: utf-8 -*-
Coupling::Application.routes.draw do
  get "index/top"
  get "index/index"

  namespace :api do

    post '/sessions/create' => 'user/sessions#create'
    get  '/sessions/verify' => 'user/sessions#verify'
    post '/sessions/destroy' => 'user/sessions#destroy'

    get  '/account/show_profile' => 'user/account#show_profile'
    post '/account/update_profile' => 'user/account#update_profile'
    post '/account/destroy' => 'user/account#destroy'

    get  '/users/list' => 'user/users#list'
    get  '/users/:id/show' => 'user/users#show'

    get  '/groups/show' => 'groups#show'
    get  '/groups/list' => 'groups#list'
    post '/groups/create' => 'groups#create'
    post '/groups/update' => 'groups#update'

    post '/friends/:id/show' => 'friends#show'
    post '/friends/create' => 'friends#create'
    post '/friends/:id/update' => 'friends#update'
    post '/friends/:id/destroy' => 'friends#destroy'

    get  '/images/list' => 'images#list'
    post '/images/create' => 'images#create'
    post '/images/:id/destroy' => 'images#destroy'
    post '/images/:id/set_main' => 'images#set_main'

    get  '/likes/list' => 'likes#list'
    post '/likes/create' => 'likes#create'
    
    get  '/favorites/list' => 'favorites#list'
    post '/favorites/create' => 'favorites#create'
    post '/favorites/destroy' => 'favorites#destroy', :as => 'favorites_destroy'

    post '/points/add' => 'points#add'
    post '/points/consume' => 'points#consume'

    post '/like_points/add' => 'like_points#add'
    post '/like_points/consume' => 'like_points#consume'

    get  '/matches/list' => 'matches#list'

    get  '/messages/list' => 'messages#list'
    post '/messages/create' => 'messages#create'

    get  '/infos/list' => 'infos#list'

    get  'receipts/list' => 'receipts#list'
    post 'receipts/validate' => 'receipts#validate'
  end

  namespace :admin do
    get  '/items/list' => 'items#list'
  end

  root :to => 'index#index'
end

app/models/member.rb
# coding:utf-8
class Member < ActiveRecord::Base
  attr_accessible :type, :blood_type, :group_id,
    :holiday, :income, :industry, :introduction, :job, 
    :nickname, :prefecture,
    :proportion, :school, :smoking, :status

  belongs_to :group

  has_one  :main_image, :class_name => "Image", :conditions => { :is_main => true }
  has_many :images, :dependent => :delete_all

  has_many :member_hobbies
  has_many :hobbies, :through => :member_hobbies
  has_many :member_specialities
  has_many :specialities, :through => :member_specialities
  has_many :member_characters
  has_many :characters, :through => :member_characters

  validates :type, :inclusion => { :in => ['Friend','Profile'] }, :presence => true
  validates :age, :presence => true
  validates :gender, 
    :presence => true,
    :inclusion => { :in => [0, 1] }
  validates :nickname, 
    :presence => true,
    :length => { :minimum => 1, :maximum => 50 }

  validates :prefecture, :inclusion => { :in => 1..47 }, :allow_nil => true
  validates :holiday, :inclusion => { :in => 0..3 }, :allow_nil => true
  validates :income, :inclusion => { :in => 0..7 }, :allow_nil => true
  validates :introduction, :length => { :minimum => 70, :maximum => 500 }, :allow_nil => true
  validates :proportion, :inclusion => { :in => 0..7 }, :allow_nil => true

  def set_main_image(image)
    ActiveRecord::Base.transaction do
      self.main_image.update_attribute(:is_main, false ) if self.main_image.present?
      image.update_attribute(:is_main, true )
    end
      return true
    rescue => e
      return false
  end

  def as_json(options = {})
      json = super(options)
      json['images'] = self.images.as_json
      json['hobbies'] = self.hobbies.as_json
      json['specialities'] = self.specialities.as_json
      json['characters'] = self.characters.as_json
      json
  end  

end

app/models/profile.rb
# coding:utf-8
class Profile < Member

  belongs_to :user
  belongs_to :group

  def assign_fb_attributes(user, fb_profile)
    params = {user_id: user.id}
    params[:age] =  get_age(fb_profile)  
    params[:gender] =  fb_profile['gender'] == "male" ? 0 : 1
    params[:nickname] =  self.nickname || get_initial(fb_profile)
    self.assign_attributes(params, :without_protection => true)
    self
  end

  def as_json(options = {})
      json = super(options)
      # json['images'] = self.images.as_json
      json
  end  

  private

  def get_initial(fb_profile)
    "#{fb_profile['first_name'][0, 1].capitalize}.#{fb_profile['last_name'][0, 1].capitalize}"
  end

  #age 誕生日を考慮していないので実際には不正確
  def get_age(fb_profile)
    Time.now.utc.to_date.year - Date.strptime(fb_profile['birthday'], '%m/%d/%Y').year
  end  
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < AdminController
  layout "profile"

  def index
    @profiles = Profile.page(params[:page])
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_profile_by_admin(params)
        format.html { redirect_to [:admin, @profile.user] }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    user = @profile.user
    @profile.destroy
    redirect_to [:admin, user], :notice => "Successfully destroyed profile."
  end
end

app/controllers/api/profiles_controller.rb
# coding:utf-8
class Api::ProfilesController < Api::BaseController
  
  def list
    profiles = Profile.by_gender(@user).order_by(params[:order], params[:direction]).page(params[:page]).per(params[:per])
    render_profiles_list(profiles)
  end

  def show
    profile = Profile.find(params[:id])
    
    render_ok(:profile => profile.as_json)
  end
end

app/views/admin/profiles/_form.html.erb
<div class="span8 offset2 well">
<%= form_for([:admin, @profile], :html => {:class => "form-horizontal well"}) do |f| %>
  <fieldset>
    <% if @profile.errors.any? %>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li class="errorMsg"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="control-group <%= 'error' if f.object.errors['status'].present? %>">
      <%= f.label :status, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :status, :class => "input-xlarge", :required => "required", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['nickname'].present? %>">
      <%= f.label :nickname, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :nickname, :class => "input-xlarge", :required => "required", :maxlength => 50 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['introduction'].present? %>">
      <%= f.label :introduction, :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :introduction, :class => "input-xlarge", :required => "required", :maxlength => 500 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['gender'].present? %>">
      <%= f.label :gender, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :gender, :class => "input-xlarge", :required => "required", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['age'].present? %>">
      <%= f.label :age, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :age, :class => "input-xlarge", :required => "required", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group date_select">
      <%= f.label :birthday_on, :class => "control-label" %>
      <div class="controls">
        <%= f.date_select :birthday_on, {include_blank: true, selected: @profile.birthday_on}, {:class => "input-mini"} %>
      </div>
    </div>    
    <div class="control-group <%= 'error' if f.object.errors['birthplace'].present? %>">
      <%= f.label :birthplace, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :birthplace, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['roommate'].present? %>">
      <%= f.label :roommate, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :roommate, :class => "input-xlarge", :maxlength => 50 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['height'].present? %>">
      <%= f.label :height, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :height, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['proportion'].present? %>">
      <%= f.label :proportion, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :proportion, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['blood_type'].present? %>">
      <%= f.label :blood_type, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :blood_type, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['marital_history'].present? %>">
      <%= f.label :marital_history, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :marital_history, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['marriage_time'].present? %>">
      <%= f.label :marriage_time, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :marriage_time, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['smoking'].present? %>">
      <%= f.label :smoking, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :smoking, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['alcohol'].present? %>">
      <%= f.label :alcohol, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :alcohol, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['industry'].present? %>">
      <%= f.label :industry, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :industry, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['job'].present? %>">
      <%= f.label :job, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :job, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['job_description'].present? %>">
      <%= f.label :job_description, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :job_description, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['workplace'].present? %>">
      <%= f.label :workplace, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :workplace, :class => "input-xlarge", :maxlength => 50 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['income'].present? %>">
      <%= f.label :income, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :income, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['school'].present? %>">
      <%= f.label :school, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :school, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['holiday'].present? %>">
      <%= f.label :holiday, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :holiday, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['sociability'].present? %>">
      <%= f.label :sociability, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :sociability, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['dislike'].present? %>">
      <%= f.label :dislike, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :dislike, :class => "input-xlarge", :maxlength => 50 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['prefecture'].present? %>">
      <%= f.label :prefecture, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :prefecture, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['character_ids'].present? %>">
      <%= f.label :character_ids, :class => "control-label" %>
      <div class="controls">
        <%= f.select :character_ids, Character.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['hobby_ids'].present? %>">
      <%= f.label :hobby_ids, :class => "control-label" %>
      <div class="controls">
        <%= f.select :hobby_ids, Hobby.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['speciality_ids'].present? %>">
      <%= f.label :speciality_ids, :class => "control-label" %>
      <div class="controls">
        <%= f.select :speciality_ids, Speciality.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit(nil, :class => "btn btn-primary", :id => "submitBtn") %>
      <%= link_to_function "戻る", "history.back()", :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/admin/profiles/edit.html.erb
<% content_for :title do %>プロフィールの更新<% end %>

<%= render 'form' %>

app/views/admin/profiles/index.html.erb
<% content_for :title do %>プロフィール管理<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>ニックネーム</th>
      <th>性別</th>
      <th>年齢</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
        <tr>
          <td><%= profile.id %></td>
          <td><%= profile.nickname %></td>
          <td><%= profile.gender %></td>
          <td><%= profile.age %></td>
          <td>
            <%= link_to "詳細", admin_profile_path(profile) %> |
            <%= link_to "編集", edit_admin_profile_path(profile) %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @profiles %>

app/views/admin/profiles/show.html.erb
<% content_for :title do %>プロフィールの詳細<% end %>

<div class="row">

  <div class="span8 offset2 well">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td width=130>ID</td>
          <td><%= @profile.id %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td><%= @profile.status %></td>
        </tr>
        <tr>
          <td>ニックネーム</td>
          <td><%= @profile.nickname %></td>
        </tr>
        <tr>
          <td>自己紹介</td>
          <td><%= @profile.introduction %></td>
        </tr>
        <tr>
          <td>性別</td>
          <td><%= @profile.gender %></td>
        </tr>
        <tr>
          <td>年齢</td>
          <td><%= @profile.age %></td>
        </tr>
        <tr>
          <td>誕生日</td>
          <td><%= @profile.birthday_on %></td>
        </tr>
        <tr>
          <td>出身</td>
          <td><%= @profile.birthplace %></td>
        </tr>
        <tr>
          <td>同居人</td>
          <td><%= @profile.roommate %></td>
        </tr>
        <tr>
          <td>身長</td>
          <td><%= @profile.height %></td>
        </tr>
        <tr>
          <td>プロポーション</td>
          <td><%= @profile.proportion %></td>
        </tr>
        <tr>
          <td>血液型</td>
          <td><%= @profile.blood_type %></td>
        </tr>
        <tr>
          <td>婚姻歴</td>
          <td><%= @profile.marital_history %></td>
        </tr>
        <tr>
          <td>婚姻期間</td>
          <td><%= @profile.marriage_time %></td>
        </tr>
        <tr>
          <td>たばこ</td>
          <td><%= @profile.smoking %></td>
        </tr>
        <tr>
          <td>アルコール</td>
          <td><%= @profile.alcohol %></td>
        </tr>
        <tr>
          <td>Industry</td>
          <td><%= @profile.industry %></td>
        </tr>
        <tr>
          <td>職業</td>
          <td><%= @profile.job %></td>
        </tr>
        <tr>
          <td>職業の内容</td>
          <td><%= @profile.job_description %></td>
        </tr>
        <tr>
          <td>勤務地</td>
          <td><%= @profile.workplace %></td>
        </tr>
        <tr>
          <td>収入</td>
          <td><%= @profile.income %></td>
        </tr>
        <tr>
          <td>学歴</td>
          <td><%= @profile.school %></td>
        </tr>
        <tr>
          <td>休日</td>
          <td><%= @profile.holiday %></td>
        </tr>
        <tr>
          <td>社交性</td>
          <td><%= @profile.sociability %></td>
        </tr>
        <tr>
          <td>苦手</td>
          <td><%= @profile.dislike %></td>
        </tr>
        <tr>
          <td>県名</td>
          <td><%= @profile.prefecture %></td>
        </tr>
        <tr>
          <td>性格</td>
          <td>
            <%= @profile.characters.map(&:name).join('、') %>
          </td>
        </tr>
        <tr>
          <td>趣味</td>
          <td>
            <%= @profile.hobbies.map(&:name).join('、') %>
          </td>
        </tr>
        <tr>
          <td>特技</td>
          <td>
            <%= @profile.specialities.map(&:name).join('、') %>
          </td>
        </tr>
        <tr>
          <td>画像</td>
          <td>
            <% @profile.images.each do |image| %>
              <%= image_tag "#{image.url}" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="pagination-centered">
      <%= link_to edit_admin_profile_path(@profile), :class => "btn btn-primary" do %><i class="icon-edit icon-white"></i>編集<% end %>
      <%= link_to admin_profile_path(@profile), :confirm => 'プロフィールを削除しますか?', :class => "btn btn-danger", :method => :delete do %><i class="icon-trash icon-white"></i>削除<% end %>
      <%= link_to "戻る", admin_user_path(@profile.user), :class => "btn" %>
    </div>
  </div>

</div>