config/routes.rb
# -*- coding: utf-8 -*-
Coupling::Application.routes.draw do
  get "index/top"
  get "index/index"

  namespace :api do

    post '/sessions/create' => 'user/sessions#create'
    get  '/sessions/verify' => 'user/sessions#verify'
    post '/sessions/destroy' => 'user/sessions#destroy'

    get  '/account/show_profile' => 'user/account#show_profile'
    post '/account/update_profile' => 'user/account#update_profile'
    post '/account/destroy' => 'user/account#destroy'

    get  '/users/list' => 'user/users#list'
    get  '/users/:id/show' => 'user/users#show'

    get  '/groups/show' => 'groups#show'
    get  '/groups/list' => 'groups#list'
    post '/groups/create' => 'groups#create'
    post '/groups/update' => 'groups#update'

    post '/friends/:id/show' => 'friends#show'
    post '/friends/create' => 'friends#create'
    post '/friends/:id/update' => 'friends#update'
    post '/friends/:id/destroy' => 'friends#destroy'

    get  '/images/list' => 'images#list'
    post '/images/create' => 'images#create'
    post '/images/:id/destroy' => 'images#destroy'
    post '/images/:id/set_main' => 'images#set_main'

    get  '/likes/list' => 'likes#list'
    post '/likes/create' => 'likes#create'
    
    get  '/favorites/list' => 'favorites#list'
    post '/favorites/create' => 'favorites#create'
    post '/favorites/destroy' => 'favorites#destroy', :as => 'favorites_destroy'

    post '/points/add' => 'points#add'
    post '/points/consume' => 'points#consume'

    post '/like_points/add' => 'like_points#add'
    post '/like_points/consume' => 'like_points#consume'

    get  '/matches/list' => 'matches#list'

    get  '/messages/list' => 'messages#list'
    post '/messages/create' => 'messages#create'

    get  '/infos/list' => 'infos#list'

    get  'receipts/list' => 'receipts#list'
    post 'receipts/validate' => 'receipts#validate'
  end

  namespace :admin do
    get  '/items/list' => 'items#list'
  end

  root :to => 'index#index'
end

app/models/friend.rb
# coding:utf-8
class Friend < Member
  attr_accessible :age, :gender

  belongs_to :group

  def create_friend(params)
    self.class.transaction do
      self.create!(params[:friend])
      self.hobbies << Hobby.where(:id => params[:hobbies])
      self.characters << Character.where(:id => params[:characters])
      self.specialities << Speciality.where(:id => params[:specialities])
    end
    true
  rescue ActiveRecord::RecordInvalid => e
    false
  rescue => e
    self.errors.add :base, e.message
    false
  end

  def as_json(options = {})
      json = super(options)
      # json['images'] = self.images.as_json
      json
  end  

end

app/models/member.rb
# coding:utf-8
class Member < ActiveRecord::Base
  attr_accessible :type, :blood_type, :group_id,
    :holiday, :income, :industry, :introduction, :job, 
    :nickname, :prefecture,
    :proportion, :school, :smoking, :status

  belongs_to :group

  has_one  :main_image, :class_name => "Image", :conditions => { :is_main => true }
  has_many :images, :dependent => :delete_all

  has_many :member_hobbies
  has_many :hobbies, :through => :member_hobbies
  has_many :member_specialities
  has_many :specialities, :through => :member_specialities
  has_many :member_characters
  has_many :characters, :through => :member_characters

  validates :type, :inclusion => { :in => ['Friend','Profile'] }, :presence => true
  validates :age, :presence => true
  validates :gender, 
    :presence => true,
    :inclusion => { :in => [0, 1] }
  validates :nickname, 
    :presence => true,
    :length => { :minimum => 1, :maximum => 50 }

  validates :prefecture, :inclusion => { :in => 1..47 }, :allow_nil => true
  validates :holiday, :inclusion => { :in => 0..3 }, :allow_nil => true
  validates :income, :inclusion => { :in => 0..7 }, :allow_nil => true
  validates :introduction, :length => { :minimum => 70, :maximum => 500 }, :allow_nil => true
  validates :proportion, :inclusion => { :in => 0..7 }, :allow_nil => true

  def set_main_image(image)
    ActiveRecord::Base.transaction do
      self.main_image.update_attribute(:is_main, false ) if self.main_image.present?
      image.update_attribute(:is_main, true )
    end
      return true
    rescue => e
      return false
  end

  def as_json(options = {})
      json = super(options)
      json['images'] = self.images.as_json
      json['hobbies'] = self.hobbies.as_json
      json['specialities'] = self.specialities.as_json
      json['characters'] = self.characters.as_json
      json
  end  

end

app/controllers/admin/friends_controller.rb
class Admin::FriendsController < AdminController
  layout "friend"

  def index
    @friends = Friend.page(params[:page])
  end

  def show
    @friend = Friend.find(params[:id])
  end

  def edit
    @friend = Friend.find(params[:id])
  end

  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_profile_by_admin(params)
        format.html { redirect_to [:admin, @friend.group.leader] }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @friend = Friend.find(params[:id])
    @leader = @friend.group.leader

    @friend.destroy
    redirect_to [:admin, @friend.group.leader], :notice => "Successfully destroyed friend."
  end
end

app/controllers/api/friends_controller.rb
class Api::FriendsController < Api::BaseController
  
  def show
    friend = Friend.find(params[:id])
    
    render_ok({friend: friend})
  end
  
  def create
    raise ActionController::RoutingError.new('Group Not Found') if @user.group.nil?

    friend = Friend.new(params[:friend])
    @user.group.friends << friend
    friend.save_profile(params)

    render_ok({friend: friend})
  end

  def update
    friend = Friend.find(params[:id])
    raise ActionController::RoutingError.new('Group Not Found') if @user.group.nil?
    raise PermissionDenied unless friend.group == @user.group

    friend.save_profile(params)

    render_ok({friend: friend})
  end  

  def destroy
    friend = Friend.find(params[:id])
    raise ActionController::RoutingError.new('Group Not Found') if @user.group.nil?
    raise PermissionDenied unless friend.group == @user.group

    friend.destroy

    render_ok
  end  
end

app/views/admin/friends/_form.html.erb
<div class="span8 offset2 well">
<%= form_for([:admin, @friend], :html => {:class => "form-horizontal well"}) do |f| %>
  <fieldset>
    <% if @friend.errors.any? %>
      <ul>
        <% @friend.errors.full_messages.each do |msg| %>
          <li class="errorMsg"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="control-group <%= 'error' if f.object.errors['status'].present? %>">
      <%= f.label :status, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :status, :class => "input-xlarge", :required => "required", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['nickname'].present? %>">
      <%= f.label :nickname, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :nickname, :class => "input-xlarge", :required => "required", :maxlength => 50 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['introduction'].present? %>">
      <%= f.label :introduction, :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :introduction, :class => "input-xlarge", :required => "required", :maxlength => 500 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['gender'].present? %>">
      <%= f.label :gender, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :gender, :class => "input-xlarge", :required => "required", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['age'].present? %>">
      <%= f.label :age, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :age, :class => "input-xlarge", :required => "required", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group date_select">
      <%= f.label :birthday_on, :class => "control-label" %>
      <div class="controls">
        <%= f.date_select :birthday_on, {include_blank: true, selected: @friend.birthday_on}, {:class => "input-mini"} %>
      </div>
    </div>    
    <div class="control-group <%= 'error' if f.object.errors['birthplace'].present? %>">
      <%= f.label :birthplace, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :birthplace, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['roommate'].present? %>">
      <%= f.label :roommate, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :roommate, :class => "input-xlarge", :maxlength => 50 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['height'].present? %>">
      <%= f.label :height, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :height, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['proportion'].present? %>">
      <%= f.label :proportion, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :proportion, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['blood_type'].present? %>">
      <%= f.label :blood_type, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :blood_type, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['marital_history'].present? %>">
      <%= f.label :marital_history, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :marital_history, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['marriage_time'].present? %>">
      <%= f.label :marriage_time, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :marriage_time, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['smoking'].present? %>">
      <%= f.label :smoking, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :smoking, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['alcohol'].present? %>">
      <%= f.label :alcohol, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :alcohol, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['industry'].present? %>">
      <%= f.label :industry, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :industry, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['job'].present? %>">
      <%= f.label :job, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :job, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['job_description'].present? %>">
      <%= f.label :job_description, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :job_description, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['workplace'].present? %>">
      <%= f.label :workplace, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :workplace, :class => "input-xlarge", :maxlength => 50 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['income'].present? %>">
      <%= f.label :income, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :income, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['school'].present? %>">
      <%= f.label :school, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :school, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['holiday'].present? %>">
      <%= f.label :holiday, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :holiday, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['sociability'].present? %>">
      <%= f.label :sociability, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :sociability, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['dislike'].present? %>">
      <%= f.label :dislike, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :dislike, :class => "input-xlarge", :maxlength => 50 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['prefecture'].present? %>">
      <%= f.label :prefecture, :class => "control-label" %>
      <div class="controls">
        <%= f.number_field :prefecture, :class => "input-xlarge", :maxlength => 10 %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['character_ids'].present? %>">
      <%= f.label :character_ids, :class => "control-label" %>
      <div class="controls">
        <%= f.select :character_ids, Character.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['hobby_ids'].present? %>">
      <%= f.label :hobby_ids, :class => "control-label" %>
      <div class="controls">
        <%= f.select :hobby_ids, Hobby.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
      </div>
    </div>
    <div class="control-group <%= 'error' if f.object.errors['speciality_ids'].present? %>">
      <%= f.label :speciality_ids, :class => "control-label" %>
      <div class="controls">
        <%= f.select :speciality_ids, Speciality.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit(nil, :class => "btn btn-primary", :id => "submitBtn") %>
      <%= link_to_function "戻る", "history.back()", :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/admin/friends/edit.html.erb
<% content_for :title do %>友人の更新<% end %>

<%= render 'form' %>

app/views/admin/friends/index.html.erb
<% content_for :title do %>友人の管理<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>ステータス</th>
      <th>Facebook ID</th>
      <th>Email</th>
      <th>ポイント</th>
      <th>最終ログイン</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.status %></td>
      <td><%= user.facebook_id %></td>
      <td><%= user.email %></td>
      <td><%= user.point %></td>
      <td><%= user.last_login_at %></td>
      <td>
        <%= link_to "詳細", admin_user_path(user) %> |
        <%= link_to "編集", edit_admin_user_path(user) %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/admin/friends/show.html.erb
<% content_for :title do %>友人の詳細<% end %>

<div class="row">

  <div class="span8 offset2 well">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td width=130>ID</td>
          <td><%= @friend.id %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td><%= @friend.status %></td>
        </tr>
        <tr>
          <td>ニックネーム</td>
          <td><%= @friend.nickname %></td>
        </tr>
        <tr>
          <td>自己紹介</td>
          <td><%= @friend.introduction %></td>
        </tr>
        <tr>
          <td>性別</td>
          <td><%= @friend.gender %></td>
        </tr>
        <tr>
          <td>年齢</td>
          <td><%= @friend.age %></td>
        </tr>
        <tr>
          <td>誕生日</td>
          <td><%= @friend.birthday_on %></td>
        </tr>
        <tr>
          <td>出身</td>
          <td><%= @friend.birthplace %></td>
        </tr>
        <tr>
          <td>同居人</td>
          <td><%= @friend.roommate %></td>
        </tr>
        <tr>
          <td>身長</td>
          <td><%= @friend.height %></td>
        </tr>
        <tr>
          <td>プロポーション</td>
          <td><%= @friend.proportion %></td>
        </tr>
        <tr>
          <td>血液型</td>
          <td><%= @friend.blood_type %></td>
        </tr>
        <tr>
          <td>婚姻歴</td>
          <td><%= @friend.marital_history %></td>
        </tr>
        <tr>
          <td>婚姻期間</td>
          <td><%= @friend.marriage_time %></td>
        </tr>
        <tr>
          <td>たばこ</td>
          <td><%= @friend.smoking %></td>
        </tr>
        <tr>
          <td>アルコール</td>
          <td><%= @friend.alcohol %></td>
        </tr>
        <tr>
          <td>Industry</td>
          <td><%= @friend.industry %></td>
        </tr>
        <tr>
          <td>職業</td>
          <td><%= @friend.job %></td>
        </tr>
        <tr>
          <td>職業の内容</td>
          <td><%= @friend.job_description %></td>
        </tr>
        <tr>
          <td>勤務地</td>
          <td><%= @friend.workplace %></td>
        </tr>
        <tr>
          <td>収入</td>
          <td><%= @friend.income %></td>
        </tr>
        <tr>
          <td>学歴</td>
          <td><%= @friend.school %></td>
        </tr>
        <tr>
          <td>休日</td>
          <td><%= @friend.holiday %></td>
        </tr>
        <tr>
          <td>社交性</td>
          <td><%= @friend.sociability %></td>
        </tr>
        <tr>
          <td>苦手</td>
          <td><%= @friend.dislike %></td>
        </tr>
        <tr>
          <td>県名</td>
          <td><%= @friend.prefecture %></td>
        </tr>
        <tr>
          <td>性格</td>
          <td>
            <%= @friend.characters.map(&:name).join('、') %>
          </td>
        </tr>
        <tr>
          <td>趣味</td>
          <td>
            <%= @friend.hobbies.map(&:name).join('、') %>
          </td>
        </tr>
        <tr>
          <td>特技</td>
          <td>
            <%= @friend.specialities.map(&:name).join('、') %>
          </td>
        </tr>
        <tr>
          <td>画像</td>
          <td>
            <% @friend.images.each do |image| %>
              <%= image_tag "#{image.url}" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="pagination-centered">
      <%= link_to edit_admin_friend_path(@friend), :class => "btn btn-primary" do %><i class="icon-edit icon-white"></i>編集<% end %>
      <%= link_to admin_friend_path(@friend), :confirm => 'プロフィールを削除しますか?', :class => "btn btn-danger", :method => :delete do %><i class="icon-trash icon-white"></i>削除<% end %>
      <%= link_to "戻る", admin_user_path(@friend.group.leader), :class => "btn" %>
    </div>
  </div>

</div>