config/routes.rb
# -*- coding: utf-8 -*-
Coupling::Application.routes.draw do
  get "index/top"
  get "index/index"

  namespace :api do

    post '/sessions/create' => 'user/sessions#create'
    get  '/sessions/verify' => 'user/sessions#verify'
    post '/sessions/destroy' => 'user/sessions#destroy'

    get  '/account/show_profile' => 'user/account#show_profile'
    post '/account/update_profile' => 'user/account#update_profile'
    post '/account/destroy' => 'user/account#destroy'

    get  '/users/list' => 'user/users#list'
    get  '/users/:id/show' => 'user/users#show'

    get  '/groups/show' => 'groups#show'
    get  '/groups/list' => 'groups#list'
    post '/groups/create' => 'groups#create'
    post '/groups/update' => 'groups#update'

    post '/friends/:id/show' => 'friends#show'
    post '/friends/create' => 'friends#create'
    post '/friends/:id/update' => 'friends#update'
    post '/friends/:id/destroy' => 'friends#destroy'

    get  '/images/list' => 'images#list'
    post '/images/create' => 'images#create'
    post '/images/:id/destroy' => 'images#destroy'
    post '/images/:id/set_main' => 'images#set_main'

    get  '/likes/list' => 'likes#list'
    post '/likes/create' => 'likes#create'
    
    get  '/favorites/list' => 'favorites#list'
    post '/favorites/create' => 'favorites#create'
    post '/favorites/destroy' => 'favorites#destroy', :as => 'favorites_destroy'

    post '/points/add' => 'points#add'
    post '/points/consume' => 'points#consume'

    post '/like_points/add' => 'like_points#add'
    post '/like_points/consume' => 'like_points#consume'

    get  '/matches/list' => 'matches#list'

    get  '/messages/list' => 'messages#list'
    post '/messages/create' => 'messages#create'

    get  '/infos/list' => 'infos#list'

    get  'receipts/list' => 'receipts#list'
    post 'receipts/validate' => 'receipts#validate'
  end

  namespace :admin do
    get  '/items/list' => 'items#list'
  end

  root :to => 'index#index'
end

app/models/image.rb
# -*- coding: utf-8 -*-
class Image < ActiveRecord::Base
  attr_accessible :member_id, :is_main

  belongs_to :member

  IMAGE_DATA_HASH = Pref::AWS::BUCKET_PATH[:image]

  def self.main_images 
    self.find(:all, :conditions => {is_main: true}, :order => 'member_id desc')
  end

  def self.create_member_iamge(member) 
    self.create!({
      member_id: member.id,
      is_main: member.main_image.nil?
      })
  end

  def url
    uploader(IMAGE_DATA_HASH).url(self.id.to_s)
  end

  def upload_parameter
    uploader(IMAGE_DATA_HASH).presigned_post(self.id.to_s)
  end

  def destroy_entity_and_file
    #TODO S3バケットのファイルも削除すること
    self.destroy
  end

  def as_json(options = {})
      json = super(options)
      json['url'] = url
      json
  end  

  private

  def uploader(hash)
    S3IndirectUploader.new(hash[:path], hash[:extension])
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController

  def index
    @images = Image.page(params[:page])
  end

  def show
    @image = Image.find(params[:id])
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to admin_images_url, :notice => "Successfully destroyed image."
  end
end

app/controllers/api/images_controller.rb
# coding:utf-8
class Api::ImagesController < Api::BaseController

  def list
    main_images = Kaminari.paginate_array(Image.main_images).page(params[:page]).per(params[:per])
    render_pagenate_data(:images, main_images, {})
  end

  def create
    raise StandardError.new("Limit Over") if @user.profile.images.count > configatron.imagess_limit - 1

    image = Image.create_member_iamge(@user.profile) 

    render_ok(image.upload_parameter)
  end

  def set_main
    image = Image.find(params[:id])
    raise PermissionDenied unless @user.profile.id == image.member.id

    @user.profile.set_main_image(image)
    render_ok
  end

  def destroy
    image = Image.find(params[:id])
    raise PermissionDenied unless @user.profile.id == image.member.id

    image.destroy_entity_and_file
    render_ok
  end
end

app/views/admin/images/index.html.erb
<% content_for :title do %>画像の一覧<% end %>
<div class="bdnavi">
  <ul class="breadcrumb">
    <li><%= yield :title =%></li>
  </ul>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>メンバーID</th>
      <th>メイン画像</th>
      <th>作成日時</th>
    </tr>
  </thead>
  <tbody>
<% @images.each do |image| %>
    <tr>
      <td><%= image.id %></td>
      <% if image.member.type == 'Profile' %>
        <td><%= link_to "#{image.member.user_id}", admin_user_path(image.member.user_id) %></td>
      <% else %>
        <td><%= link_to "#{image.member_id}", admin_friend_path(image.member_id) %></td>
      <% end %>
      <td><%= image.is_main %></td>
      <td><%= image.created_at %></td>
      <td>
        <%= link_to "詳細", admin_image_path(image) %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<%= paginate @images %>

app/views/admin/images/show.html.erb
<% content_for :title do %>画像の詳細<% end %>
<div class="bdnavi">
  <ul class="breadcrumb">
    <li><%= link_to "画像の一覧", [:admin, :images] %> &gt;</li>
    <li><%= yield :title =%></li>
  </ul>
</div>

<div class="row">
  <div class="span8 offset2 well">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td>ID</td>
          <td><%= @image.id %></td>
        </tr>
        <tr>
          <td>メンバーID</td>
          <% if @image.member.type == 'Profile' %>
            <td><%= link_to "#{@image.member.user_id}", admin_user_path(@image.member.user_id) %></td>
          <% else %>
            <td><%= link_to "#{@image.member_id}", admin_friend_path(@image.member_id) %></td>
          <% end %>
        </tr>
        <tr>
          <td>メイン画像</td>
          <td><%= @image.is_main %></td>
        </tr>
        <tr>
          <td>作成日時</td>
          <td><%= @image.created_at %></td>
        </tr>
        <tr>
          <td>画像</td>
          <td><%= image_tag "#{@image.url}" %></td>
        </tr>
      </tbody>
    </table>
    <div class="pagination-centered">
      <%= link_to [:admin, @image], :confirm => '画像を削除しますか?', :class => "btn btn-danger", :method => :delete do %><i class="icon-trash icon-white"></i>削除<% end %>
      <%= link_to "戻る", admin_images_path, :class => "btn" %>
    </div>
  </div>
</div>