config/routes.rb
# -*- coding: utf-8 -*-
Coupling::Application.routes.draw do
  get "index/top"
  get "index/index"

  namespace :api do

    post '/sessions/create' => 'user/sessions#create'
    get  '/sessions/verify' => 'user/sessions#verify'
    post '/sessions/destroy' => 'user/sessions#destroy'

    get  '/account/show_profile' => 'user/account#show_profile'
    post '/account/update_profile' => 'user/account#update_profile'
    post '/account/destroy' => 'user/account#destroy'

    get  '/users/list' => 'user/users#list'
    get  '/users/:id/show' => 'user/users#show'

    get  '/groups/show' => 'groups#show'
    get  '/groups/list' => 'groups#list'
    post '/groups/create' => 'groups#create'
    post '/groups/update' => 'groups#update'

    post '/friends/:id/show' => 'friends#show'
    post '/friends/create' => 'friends#create'
    post '/friends/:id/update' => 'friends#update'
    post '/friends/:id/destroy' => 'friends#destroy'

    get  '/images/list' => 'images#list'
    post '/images/create' => 'images#create'
    post '/images/:id/destroy' => 'images#destroy'
    post '/images/:id/set_main' => 'images#set_main'

    get  '/likes/list' => 'likes#list'
    post '/likes/create' => 'likes#create'
    
    get  '/favorites/list' => 'favorites#list'
    post '/favorites/create' => 'favorites#create'
    post '/favorites/destroy' => 'favorites#destroy', :as => 'favorites_destroy'

    post '/points/add' => 'points#add'
    post '/points/consume' => 'points#consume'

    post '/like_points/add' => 'like_points#add'
    post '/like_points/consume' => 'like_points#consume'

    get  '/matches/list' => 'matches#list'

    get  '/messages/list' => 'messages#list'
    post '/messages/create' => 'messages#create'

    get  '/infos/list' => 'infos#list'

    get  'receipts/list' => 'receipts#list'
    post 'receipts/validate' => 'receipts#validate'
  end

  namespace :admin do
    get  '/items/list' => 'items#list'
  end

  root :to => 'index#index'
end

app/models/user.rb
# -*r coding: utf-8 -*-
class User < ActiveRecord::Base

  # attr_protected :access_token, :age, :email, :facebook_id, :like_point, 
  #   :gender, :point, :last_login_at, :invitation_code, :status, :public_status
  
  has_one  :profile
  has_one  :group
  has_many :receipts, :dependent => :delete_all, :order => 'created_at desc'
  has_many :favorites, :dependent => :delete_all, :order => 'created_at desc'
  has_many :likes, :dependent => :delete_all, :order => 'created_at desc'
  has_many :likeds, :class_name => "Like", :foreign_key => "target_id", :dependent => :delete_all, :order => 'created_at desc'
  has_many :matches, :dependent => :delete_all, :order => 'created_at desc'

  has_many :favorite_users, :through => :favorites, :source => :target_user, :include => [:profile], :uniq => true
  has_many :like_users, :through => :likes, :source => :target_user, :include => [:profile], :uniq => true
  has_many :liked_users, :through => :likeds, :source => :user, :include => [:profile], :uniq => true
  has_many :match_users, :through => :matches, :source => :target_user, :include => [:profile], :uniq => true

  validates :access_token, :presence => true
  validates :facebook_id, :presence => true

  def self.create_or_find_by_access_token(access_token, device_token)
    graph = Koala::Facebook::API.new(access_token)
    fb_profile = graph.get_object("me") 

    user = self.find_by_facebook_id(fb_profile[:id].to_i)
    user = self.new if user.nil?
    user.assign_fb_attributes(fb_profile, access_token, device_token)
    user.save!
    profile = user.profile.nil? ? Profile.new : user.profile
    profile.assign_fb_attributes(user, fb_profile)
    profile.save!
    user.profile = profile
    user
  end

  def self.where_cond(params)
    cond = self.where(gender: params[:gender])
    if params[:prefecture].present?
      ids = Profile.where(prefecture: params[:prefecture]).map(&:user_id)
      cond = cond.where(["id in (?)", ids])
    end
    if params[:age].present?
      ids = Profile.where(age: params[:age]).map(&:user_id)
      cond = cond.where(["id in (?)", ids])
    end
    if params[:income].present?
      ids = Profile.where(sincome: params[:income]).map(&:user_id)
      cond = cond.where(["id in (?)", ids])
    end
    cond
  end

  def infos
    Info.find(:all, :conditions => ['target_id IN (?,?)', -1, self.id] , :order => 'created_at desc')
  end

  def like?(target)
    Like.find_by_user_id_and_target_id(self.id, target.id).present?
  end

  def liked?(target)
    Like.find_by_user_id_and_target_id(target.id, self.id).present?
  end

  def match?(target)
    Match.find_by_user_id_and_target_id(self.id, target.id).present?
  end

  def over_likes_limit_per_day?
    self.likes.where('created_at > ?', Date.today).count > configatron.likes_limit_per_day - 1
  end

  # targetに対するLikeを作る
  # 既にmatchがあれば何もしない。
  # 相手からLikeされていれば、Matchに切り替える。
  # 上記以外はtargetに対するLikeを作成。
  def create_like(target)
    return {type: "match"} if self.match?(target)

    if liked?(target)
      self.create_match(target)
    else
      begin
        self.like_users << target
      rescue Exception => e
        ActiveRecord::Rollback
        return {message: "internal_server_error"}
      else
        return {type: "like"}
      end          
    end
  end

  def create_match(target)
    ActiveRecord::Base.transaction do
      target.like_users.delete self
      self.match_users << target
      target.match_users << self
    end
      return {type: "match"}
    rescue => e
      return {message: "internal_server_error"}    
  end

  def add_point(amount)
    if amount > 0
      begin
        self.point += amount
        self.save!
      rescue ActiveRecord::RecordInvalid => e
        self.errors.add :base, "internal_server_error"
        false
      end
    else
      self.errors.add :base, "invalid_arguments"
      false
    end
  end

  def consume_point(amount)
    if amount > 0 && amount < self.point
      begin
        self.point -= amount
        self.save!
      rescue ActiveRecord::RecordInvalid => e
        self.errors.add :base, "internal_server_error"
        false
      end
    else
      self.errors.add :base, "invalid_arguments"
      false
    end
  end

  def add_like_point(amount)
    if amount > 0
      begin
        self.like_point += amount
        self.save!
      rescue ActiveRecord::RecordInvalid => e
        self.errors.add :base, "internal_server_error"
        false
      end
    else
      self.errors.add :base, "invalid_arguments"
      false
    end
  end

  def consume_like_point(amount)
    if amount > 0 && amount < self.like_point
      begin
        self.like_point -= amount
        self.save!
      rescue ActiveRecord::RecordInvalid => e
        self.errors.add :base, "internal_server_error"
        false
      end
    else
      self.errors.add :base, "invalid_arguments"
      false
    end
  end

=begin
    FacebookIDとアクセストークンを渡すとプロフィールの情報を更新する。
    TODO 最終ログインの更新
    TODO バリデーション

    Facebook response
    {
      "id"=>"123456", 
      "name"=>"First Middle Last", 
      "first_name"=>"First", 
      "middle_name"=>"Middle", 
      "last_name"=>"Last", 
      "link"=>"http://www.facebook.com/MyName", 
      "username"=>"my.name", 
      "birthday"=>"12/12/1212", 
      "hometown"=>{"id"=>"115200305133358163", "name"=>"City, State"}, "location"=>{"id"=>"1054648928202133335", "name"=>"City, State"}, 
      "bio"=>"This is my awesome Bio.", 
      "quotes"=>"I am the master of my fate; I am the captain of my soul. - William Ernest Henley\r\n\r\n"Don't go around saying the world owes you a living. The world owes you nothing. It was here first.\" - Mark Twain", 
      "work"=>[{"employer"=>{"id"=>"100751133333", "name"=>"Company1"}, "position"=>{"id"=>"105763693332790962", "name"=>"Position1"}, "start_date"=>"2010-08", "end_date"=>"2011-07"}],
      "sports"=>[{"id"=>"104019549633137", "name"=>"Sport1"}, {"id"=>"103992339636529", "name"=>"Sport2"}], 
      "favorite_teams"=>[{"id"=>"105467226133353743", "name"=>"Fav1"}, {"id"=>"19031343444432369133", "name"=>"Fav2"}, {"id"=>"98027790139333", "name"=>"Fav3"}, {"id"=>"104055132963393331", "name"=>"Fav4"}, {"id"=>"191744431437533310", "name"=>"Fav5"}], 
      "favorite_athletes"=>[{"id"=>"10836600585799922", "name"=>"Fava1"}, {"id"=>"18995689436787722", "name"=>"Fava2"}, {"id"=>"11156342219404022", "name"=>"Fava4"}, {"id"=>"11169998212279347", "name"=>"Fava5"}, {"id"=>"122326564475039", "name"=>"Fava6"}], 
      "inspirational_people"=>[{"id"=>"16383141733798", "name"=>"Fava7"}, {"id"=>"113529011990793335", "name"=>"fava8"}, {"id"=>"112032333138809855566", "name"=>"Fava9"}, {"id"=>"10810367588423324", "name"=>"Fava10"}], 
      "education"=>[{"school"=>{"id"=>"13478880321332322233663", "name"=>"School1"}, "type"=>"High School", "with"=>[{"id"=>"1401052755", "name"=>"Friend1"}]}, {"school"=>{"id"=>"11482777188037224", "name"=>"School2"}, "year"=>{"id"=>"138383069535219", "name"=>"2005"}, "type"=>"High School"}, {"school"=>{"id"=>"10604484633093514", "name"=>"School3"}, "year"=>{"id"=>"142963519060927", "name"=>"2010"}, "concentration"=>[{"id"=>"10407695629335773", "name"=>"c1"}], "type"=>"College"}, {"school"=>{"id"=>"22030497466330708", "name"=>"School4"}, "degree"=>{"id"=>"19233130157477979", "name"=>"c3"}, "year"=>{"id"=>"201638419856163", "name"=>"2011"}, "type"=>"Graduate School"}], 
      "gender"=>"male", 
      "interested_in"=>["female"], 
      "relationship_status"=>"Single", 
      "religion"=>"Religion1", 
      "political"=>"Political1", 
      "email"=>"somename@somecompany.com", 
      "timezone"=>-8, 
      "locale"=>"en_US", 
      "languages"=>[{"id"=>"10605952233759137", "name"=>"English"}, {"id"=>"10337617475934611", "name"=>"L2"}, {"id"=>"11296944428713061", "name"=>"L3"}], 
      "verified"=>true,
      "updated_time"=>"2012-02-24T04:18:05+0000"
    }
=end
  def assign_fb_attributes(fb_profile, access_token, device_token)
    params = {access_token: access_token}
      # params.picture = graph.get_picture(uid) 
    params[:device_token] = device_token unless device_token.nil?      
    params[:email] =        fb_profile[:email] 
    params[:facebook_id] =  self.facebook_id || fb_profile['id']
    params[:gender] =  fb_profile[:gender] == "male" ? 0 : 1
    params[:last_login_at] = Time.now      
    self.assign_attributes(params, :without_protection => true)
    self
  end

  def as_json(options = {})
      json = super(options)
      json['profile'] = self.profile.as_json
      json
  end  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  layout "user"

  def index
    @users = User.by_keyword(params[:field], params[:keyword]).
      order_by(params[:field], params[:direction]).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(params[:user], :as => :admin)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user] }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, :notice => "Successfully destroyed user."
  end
end

app/controllers/api/user/account_controller.rb
# coding:utf-8
class Api::User::AccountController < Api::BaseController

  def show_profile
    render_ok(:profile => @user.profile.as_json)
  end

  def update_profile
    @user.profile.save_profile(params)
    render_ok(:profile => @user.profile.as_json)
  end

  def destroy
    @user.destroy
    render_ok
  end
end

app/controllers/api/user/sessions_controller.rb
# -*- coding: utf-8 -*-
class Api::User::SessionsController < Api::BaseController
  skip_before_filter :verify_session, :only => [:create]

  def create
    raise BadRequest.new('access_token required') unless params[:access_token]

    @user = ::User.create_or_find_by_access_token(params[:access_token], params[:device_token])
    @session = Session.create_session(@user)
    render_ok(user_hash)
  end

  #セッションIDをverifyする
  def verify
    if @user.last_verify_at < Date.today
      @login_bonus = configatron.login_bonus
      @user.assign_attributes({point: @user.point + @login_bonus, last_verify_at: Time.now}, :without_protection => true)
      @user.save
    end
    render_ok(user_hash)
  end

  #ログアウト。セッションを破棄する
  def destroy
    @session.destroy
    render_ok
  end

  private

  def user_hash
    {
      :session => @session.key,
      :user => @user.as_json(:only => [:id, :status, :point, :like_point, :last_login_at]),
      :login_bonus => @login_bonus
    }
  end
end

app/controllers/api/user/users_controller.rb
# coding:utf-8
class Api::User::UsersController < Api::BaseController
  
  def list
    gender = @user.gender == 0 ? 1 : 0
    cond_param = { 
      gender: gender,
      prefecture: params[:prefecture],
      age: params[:age],
      income: params[:income]
    }
    cond = User.where_cond(cond_param)
    users = Kaminari.paginate_array(cond).page(params[:page]).per(params[:per])
    render_users_list(users)
  end

  def show
    user = User.find_by_id(params[:id])
    render_not_found and return if user.nil?
    
    render_ok(:user => user.as_json(:only => [:id]))
  end
end

app/controllers/api/user_controller.rb
# coding:utf-8
class Api::UserController < Api::BaseController
  def profile_get
    @users = User.where(:facebook_id => params[:facebook_id])
    if @users.present?
      render_ok(@users)
    else
      render_ng
    end
  end

  def profile_post
    render_ok
  end

  def list
    @users = User.limit(10)
    render_ok(@users)
  end

  def like_get
    @likes = Like.limit(10)
    render_ok(@likes)
  end

  def like_post
    render_ok
  end

  def favorite_get
    @favorites = Favorite.limit(10)
    render_ok(@favorites)
  end

  def favorite_post
    render :text => 'this is favorite_post'
  end

  def likelist
    @likes = Like.all().limit(10)
    render_ok(@likes)
  end

  def block_get

  end

  def block_post
    redner_ok
  end

  def blocklist
  end

  def talk_get
    return_hash = {
                'talk-2' => {:facebook_id => 12345678,
                             :message => 'こんにちは'},
                'talk-1' => {:facebook_id => 12345678,
                             :message => 'はじめまして'}
               }
    render_ok(return_hash)
  end

  def talk_post
    render_ok
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/edit.html.erb
<% content_for :title do %>ユーザー情報の更新<% end %>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<% content_for :title do %>ユーザー一覧<% end %>

<div class="input-append">
  <input class="span3" id="keyword" type="text">
  <div class="btn-group">
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      Action
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#" class="search" data-type="id">ユーザーIDを検索</a></li>
      <li><a href="#" class="search" data-type="nickname">ニックネームを検索</a></li>
      <li><a href="#" class="search" data-type="email">Emailを検索</a></li>
      <li><a href="#" class="search" data-type="facebook_id">FacebookIDを検索</a></li>
    </ul>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>ステータス</th>
      <th>Facebook ID</th>
      <th>Email</th>
      <th>ポイント</th>
      <th>最終ログイン</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.status %></td>
      <td><%= user.facebook_id %></td>
      <td><%= user.email %></td>
      <td><%= user.point %></td>
      <td><%= user.last_login_at %></td>
      <td>
        <%= link_to "詳細", admin_user_path(user) %> |
        <%= link_to "編集", edit_admin_user_path(user) %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/admin/users/show.html.erb
<% content_for :title do %><%= @user.profile.nickname %><% end %>

<div class="row">
  <div class="span8 well">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td>ID</td>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td><%= @user.status %></td>
        </tr>
        <tr>
          <td>Facebook ID</td>
          <td><%= @user.facebook_id %></td>
        </tr>
        <tr>
          <td>Email</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>Access Token</td>
          <td><%= truncate(@user.access_token, :length => 50) %></td>
        </tr>
        <tr>
          <td>Device Token</td>
          <td><%= @user.device_token %></td>
        </tr>
        <tr>
          <td>招待コード</td>
          <td><%= @user.invitation_code %></td>
        </tr>
        <tr>
          <td>Contact Type</td>
          <td><%= @user.contract_type %></td>
        </tr>
        <tr>
          <td>ポイント</td>
          <td><%= @user.point %></td>
        </tr>
        <tr>
          <td>likeポイント</td>
          <td><%= @user.like_point %></td>
        </tr>
        <tr>
          <td>最終ログイン</td>
          <td><%= @user.last_login_at %></td>
        </tr>
        <tr>
          <td>最終Verify</td>
          <td><%= @user.last_verify_at %></td>
        </tr>
        <tr>
          <td>入会日時</td>
          <td><%= @user.created_at %></td>
        </tr>
      </tbody>
    </table>
    <div class="pagination-centered">
      <%= link_to edit_admin_user_path(@user), :class => "btn btn-primary" do %><i class="icon-edit icon-white"></i>編集<% end %>
      <%= link_to [:admin, @user], :confirm => 'ユーザーを削除しますか?', :class => "btn btn-danger", :method => :delete do %><i class="icon-trash icon-white"></i>削除<% end %>
      <%= link_to "戻る", admin_users_path, :class => "btn" %>
    </div>
  </div>

  <div class="span3 well">
    <ul>
      <li><%= link_to "お気に入りのユーザー", admin_user_favorites_path(@user) %>(<%= @user.favorites.count %>)</li>
      <li><%= link_to "いいねしたユーザー", admin_user_likes_path(@user) %>(<%= @user.likes.count %>)</li>
      <li><%= link_to "マッチしたユーザー", admin_user_matches_path(@user) %>(<%= @user.matches.count %>)</li>
      <li><%= link_to "送ったメッセージ", admin_user_messages_path(@user) %>(<%= @user.messages.count %>)</li>
      <li><%= link_to "購入したアイテム", admin_user_receipts_path(@user) %>(<%= @user.receipts.count %>)</li>
      <li><%= link_to "受信した通知", admin_user_infos_path(@user) %>(<%= @user.received_infos.count %>)</li>
    </ul>
  </div>

  <% if @user.profile.present? %>
    <div class="span8 well">
      <h3>プロフィール</h3>
      <% profile = @user.profile %>
      <table class="table table-striped">
        <tbody>
          <tr>
            <td width=130>ID</td>
            <td><%= profile.id %></td>
          </tr>
          <tr>
            <td>ステータス</td>
            <td><%= profile.status %></td>
          </tr>
          <tr>
            <td>ニックネーム</td>
            <td><%= profile.nickname %></td>
          </tr>
          <tr>
            <td>自己紹介</td>
            <td><%= profile.introduction %></td>
          </tr>
          <tr>
            <td>性別</td>
            <td><%= profile.gender %></td>
          </tr>
          <tr>
            <td>年齢</td>
            <td><%= profile.age %></td>
          </tr>
          <tr>
            <td>誕生日</td>
            <td><%= profile.birthday_on %></td>
          </tr>
          <tr>
            <td>出身</td>
            <td><%= profile.birthplace %></td>
          </tr>
          <tr>
            <td>同居人</td>
            <td><%= profile.roommate %></td>
          </tr>
          <tr>
            <td>身長</td>
            <td><%= profile.height %></td>
          </tr>
          <tr>
            <td>プロポーション</td>
            <td><%= profile.proportion %></td>
          </tr>
          <tr>
            <td>血液型</td>
            <td><%= profile.blood_type %></td>
          </tr>
          <tr>
            <td>婚姻歴</td>
            <td><%= profile.marital_history %></td>
          </tr>
          <tr>
            <td>婚姻期間</td>
            <td><%= profile.marriage_time %></td>
          </tr>
          <tr>
            <td>たばこ</td>
            <td><%= profile.smoking %></td>
          </tr>
          <tr>
            <td>アルコール</td>
            <td><%= profile.alcohol %></td>
          </tr>
          <tr>
            <td>Industry</td>
            <td><%= profile.industry %></td>
          </tr>
          <tr>
            <td>職業</td>
            <td><%= profile.job %></td>
          </tr>
          <tr>
            <td>職業の内容</td>
            <td><%= profile.job_description %></td>
          </tr>
          <tr>
            <td>勤務地</td>
            <td><%= profile.workplace %></td>
          </tr>
          <tr>
            <td>収入</td>
            <td><%= profile.income %></td>
          </tr>
          <tr>
            <td>学歴</td>
            <td><%= profile.school %></td>
          </tr>
          <tr>
            <td>休日</td>
            <td><%= profile.holiday %></td>
          </tr>
          <tr>
            <td>社交性</td>
            <td><%= profile.sociability %></td>
          </tr>
          <tr>
            <td>苦手</td>
            <td><%= profile.dislike %></td>
          </tr>
          <tr>
            <td>県名</td>
            <td><%= profile.prefecture %></td>
          </tr>
          <tr>
            <td>性格</td>
            <td>
              <%= profile.characters.map(&:name).join('、') %>
            </td>
          </tr>
          <tr>
            <td>趣味</td>
            <td>
              <%= profile.hobbies.map(&:name).join('、') %>
            </td>
          </tr>
          <tr>
            <td>特技</td>
            <td>
              <%= profile.specialities.map(&:name).join('、') %>
            </td>
          </tr>
          <tr>
            <td>画像</td>
            <td>
              <% profile.images.each do |image| %>
　              <%= link_to(image_tag("#{image.url}"), admin_image_path(image)) %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="pagination-centered">
        <%= link_to [:edit, :admin, @user, profile], :class => "btn btn-primary" do %><i class="icon-edit icon-white"></i>編集<% end %>
        <%= link_to [:admin, @user, profile], :confirm => 'プロフィールを削除しますか?', :class => "btn btn-danger", :method => :delete do %><i class="icon-trash icon-white"></i>削除<% end %>
      </div>
    </div>
  <% end %>

  <% if @user.group.present? %>
    <div class="span8 well">
      <h3>グループ</h3>
      <% group = @user.group %>
      <table class="table table-striped">
        <tbody>
          <tr>
            <td width=130>ID</td>
            <td><%= group.id %></td>
          </tr>
          <tr>
            <td>ステータス</td>
            <td><%= group.status %></td>
          </tr>
          <tr>
            <td>性別</td>
            <td><%= group.gender %></td>
          </tr>
          <tr>
            <td>年齢(最年長)</td>
            <td><%= group.max_age %></td>
          </tr>
          <tr>
            <td>年齢(最年少)</td>
            <td><%= group.min_age %></td>
          </tr>
          <tr>
            <td>人数</td>
            <td><%= group.head_count %></td>
          </tr>
          <tr>
            <td>関係</td>
            <td><%= group.relationship %></td>
          </tr>
          <tr>
            <td>要望</td>
            <td><%= group.request %></td>
          </tr>
          <tr>
            <td>開始時間</td>
            <td><%= group.opening_hour %></td>
          </tr>
          <tr>
            <td>対象とする年齢</td>
            <td><%= group.target_age_range %></td>
          </tr>
          <tr>
            <td>エリア</td>
            <td><%= group.area %></td>
          </tr>
          <tr>
            <td>グループイメージ</td>
            <td>
              <%= group.group_images.map(&:name).join('、') %>
            </td>
          </tr>
          <tr>
            <td>対象とする県</td>
            <td>
              <%= group.mst_prefectures.map(&:name).join('、') %>
            </td>
          </tr>
          <tr>
            <td>可能な曜日</td>
            <td>
              <%= group.days.map(&:name).join('、') %>
            </td>
          </tr>          
        </tbody>
      </table>
      <div class="pagination-centered">
        <%= link_to [:edit, :admin, @user, group], :class => "btn btn-primary" do %><i class="icon-edit icon-white"></i>編集<% end %>
        <%= link_to [:admin, @user, group], :confirm => 'グループを削除しますか?', :class => "btn btn-danger", :method => :delete do %><i class="icon-trash icon-white"></i>削除<% end %>
      </div>
    </div>

    <div class="span8 well">
      <h3>グループの友人</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>ニックネーム</th>
            <th>性別</th>
            <th>年齢</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% group.friends.each do |friend| %>
              <tr>
                <td><%= friend.id %></td>
                <td><%= friend.nickname %></td>
                <td><%= friend.gender %></td>
                <td><%= friend.age %></td>
                <td>
                  <%= link_to "詳細", [:admin, @user, group, friend] %> |
                  <%= link_to "編集", [:edit, :admin, @user, group, friend] %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>